replicaCount: 1

deployments:
  default:
    enabled: true

image:  
  repository: "sa-saopaulo-1.ocir.io/gr03pmgkbzvm/devops/ms-java-springboot"  
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: "ocireg"

service:
  enabled: true
  type: ClusterIP

autoscaling:
  enabled: false

keda:
  enabled: false

podDisruptionBudget:
  enabled: false

verticalPodAutoscaler:
  enabled: false

podAntiAffinity:
  enabled: false

ingress:
  enabled: false

secrets:
  - name: ocireg
    values:
      KEY_NAME3: DECODED_VALUE
      
argo:
  rollouts:
    enabled: false